version: "3"

services:
  apt-cacher-ng:
    build:
      context: ./apt_cacher_ng
    ports:
      - 3142:3142

  knowrob:
    build:
      context: ./knowrob
      network: host # Allow access to localhost
      args:
        APT_CACHER_NG_HOST: localhost
        APT_CACHER_NG_PORT: 3142
